### ISSUE TITLE
pbLoading must not be null

### ISSUE THREAD

**Issue by jmadaminov** [click-llc/android-msdk#1]
Fatal Exception: java.lang.IllegalStateException
pbLoading must not be null
uz.click.mobilesdk.impl.PaymentConfirmationFragment$hideLoading$1.run (PaymentConfirmationFragment.kt:150)

**Comment by FayzullayevRasulbek** [comment]
thanks, will be fixed in next version

**Comment by Islomov49** [comment]
fixed in version: 1.1.1
