### ISSUE TITLE
App crashed when I allow R8 to obfuscate my project

### ISSUE THREAD

**Issue by raheemadamboev** [click-llc/android-msdk#3]
It was all going well before obfuscation and shrinking. After R8 obfuscate, if I want to show Click fragment it crashes.
I searched a lot the cause of the crash from internet and found that third party libraries should write proper proguard rules. I don't know again.
![photo_2020-10-31_03-40-11](https://user-images.githubusercontent.com/67774375/97762579-cdc8d700-1b2a-11eb-9eae-9c7ca5ed064b.jpg)

**Comment by Islomov49** [comment]
Yes, the library can contain proguard rules.. But if you use R8, you should also have a good understanding of how this technology works. If you do not know how to configure proguard rules configs, you may have problems with other libraries in the same way.

The error can be solved simply by disabling R8 for our library.

Open your "proguard-rules.pro" file, in your project 
Add:
```
-keep class uz.click.mobilesdk.** { *; }
-dontwarn uz.click.mobilesdk.**
```
This should fix the problem.

**Comment by raheemadamboev** [comment]
> Yes, the library can contain proguard rules.. But if you use R8, you should also have a good understanding of how this technology works. If you do not know how to configure proguard rules configs, you may have problems with other libraries in the same way.
> 
> The error can be solved simply by disabling R8 for our library.
> 
> Open your "proguard-rules.pro" file, in your project
> Add:
> 
> ```
> -keep class uz.click.mobilesdk.** { *; }
> -dontwarn uz.click.mobilesdk.**
> ```
> 
> This should fix the problem.

Yes thanks man, u solved my problem. It worked
