### ISSUE TITLE
 kotlin.UninitializedPropertyAccessException: lateinit property themeMode has not been initialized

### ISSUE THREAD

**Issue by raheemadamboev** [click-llc/android-msdk#4]
If I want to scan my card it throws exception.

![Screenshot - 11_2_2020 , 4_03_05 PM](https://user-images.githubusercontent.com/67774375/97862066-8dce4380-1d26-11eb-8fdf-45b1920b4b53.png)

I guess I initialized themeMode

![Screenshot - 11_2_2020 , 4_06_54 PM](https://user-images.githubusercontent.com/67774375/97862090-99216f00-1d26-11eb-9027-1500582cc5d3.png)

And fragment working with both themes if I change the theme of app
![photo_2020-11-02_16-18-06](https://user-images.githubusercontent.com/67774375/97862358-01705080-1d27-11eb-9f77-345656bec815.jpg)
![photo_2020-11-02_16-18-02](https://user-images.githubusercontent.com/67774375/97862361-02a17d80-1d27-11eb-937e-09dd15a3d8d8.jpg)

What should I do?

**Comment by Islomov49** [comment]
Thanks, It is bug. We will fix it in 1.2.2 version. Maximum in 2 days will be released

**Comment by Islomov49** [comment]
FIXED

**Comment by Islomov49** [comment]
@raheemideadev fixed and released with version 1.2.2

**Comment by raheemadamboev** [comment]
> @raheemideadev fixed and released with version 1.2.2

thanks for notifying

may I disable scan function, because it requires camera permission
can I use this repository without adding camera permission to the manifest

My app is about education and I guess it does not require camera

![Screenshot - 11_3_2020 , 12_42_53 AM](https://user-images.githubusercontent.com/67774375/97912540-c265ed80-1d6e-11eb-9cb3-d0d98653d6e8.png)
![Screenshot - 11_3_2020 , 12_57_32 AM](https://user-images.githubusercontent.com/67774375/97913177-c8100300-1d6f-11eb-8837-a307e174749b.png)

**Comment by Islomov49** [comment]
The permission is written in the sdk manifest, it cannot be configured. In fact, you never meet these unsupported smartphone models.

**Comment by Islomov49** [comment]
@raheemideadev You can disable it in your manifest https://stackoverflow.com/questions/37417259/disable-dependency-library-permission

**Comment by Islomov49** [comment]
For you case, you should add this code in your Manifest:
```
<uses-permission
        android:name="android.permission.CAMERA"
        tools:node="remove" />
```
